 property:
    test:
        name: property depth test
 propertyTestList: a,b,c
 frult:
     list:
         - name: banana
           color: yellow
         - name: apple
           color: redz
         - name: water melon
           color: green
 server:
   port: 80
   
 spring:
    profiles: local
    banner:
        image:
            location: banner.txt
    
 
          
 
